//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.TitleTbls = new HashSet<TitleTbl>();
        }
    
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Order { get; set; }
        public string dsc { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RepeatCount { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public Nullable<int> RepeatedNumber { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TitleTbl> TitleTbls { get; set; }
    }
}
