//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataCard
    {
        public int DataCardId { get; set; }
        public int personelid { get; set; }
        public string DateCard { get; set; }
        public int I { get; set; }
        public int O { get; set; }
    }
}
