//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaysExercise
    {
        public int Id { get; set; }
        public string DateExercise { get; set; }
        public Nullable<int> WordId { get; set; }
        public Nullable<bool> Succ_OR_UnSucc { get; set; }
    
        public virtual dic_tbl dic_tbl { get; set; }
    }
}
