//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_tbl_LOG
    {
        public int id { get; set; }
        public string eng { get; set; }
        public string per { get; set; }
        public Nullable<int> level { get; set; }
        public string date_s { get; set; }
        public string date_refresh { get; set; }
        public string time { get; set; }
        public Nullable<int> timeword { get; set; }
        public Nullable<int> id_month { get; set; }
        public Nullable<int> minuteWord { get; set; }
        public string HostName_TrgLog { get; set; }
        public string LoginName_TrgLog { get; set; }
        public string LogStatus_TrgLog { get; set; }
        public string TimeDate_TrgLog { get; set; }
    }
}
