//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dic_tbl()
        {
            this.DaysExercises = new HashSet<DaysExercise>();
            this.example_tbl = new HashSet<example_tbl>();
        }
    
        public int id { get; set; }
        public string eng { get; set; }
        public string per { get; set; }
        public string Phonetic { get; set; }
        public int level { get; set; }
        public string date_s { get; set; }
        public string date_refresh { get; set; }
        public string time { get; set; }
        public Nullable<int> timeword { get; set; }
        public Nullable<int> id_month { get; set; }
        public Nullable<int> SuccessCount { get; set; }
        public Nullable<int> UnSuccessCount { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreateDateM { get; set; }
        public Nullable<System.DateTime> DateRefreshM { get; set; }
        public Nullable<bool> IsArchieve { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaysExercise> DaysExercises { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<example_tbl> example_tbl { get; set; }
    }
}
