//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class example_tbl
    {
        public int id { get; set; }
        public int id_dic_tbl { get; set; }
        public string example { get; set; }
    
        public virtual dic_tbl dic_tbl { get; set; }
    }
}
