//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class IODayly
    {
        public int IOId { get; set; }
        public Nullable<int> STime { get; set; }
        public Nullable<int> ETime { get; set; }
        public Nullable<int> IOType { get; set; }
        public string DayDate { get; set; }
    }
}
