//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kharj
    {
        public int KharjId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rial { get; set; }
        public string Description { get; set; }
        public string DateKharj { get; set; }
        public Nullable<int> KharjTypeId { get; set; }
    
        public virtual KharjType KharjType { get; set; }
    }
}
