//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> IsCascade { get; set; }
        public string Url { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
    }
}
