//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Namad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Namad()
        {
            this.NamadDetails = new HashSet<NamadDetail>();
        }
    
        public int Id { get; set; }
        public string Namad1 { get; set; }
        public string CodeSherkat { get; set; }
        public string tseAdrs { get; set; }
        public Nullable<int> RahavardId { get; set; }
        public string NamadSahih { get; set; }
        public string tseId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NamadDetail> NamadDetails { get; set; }
    }
}
