//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamadDetail
    {
        public int Id { get; set; }
        public Nullable<int> NamadId { get; set; }
        public string ShamsyDate { get; set; }
        public Nullable<long> Hajm { get; set; }
        public Nullable<long> TedadMoamelat { get; set; }
        public Nullable<double> DarsadGheymatPayany { get; set; }
        public Nullable<long> GheymatPayany { get; set; }
    
        public virtual Namad Namad { get; set; }
    }
}
