//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerScore
    {
        public int PlayerScoreId { get; set; }
        public int UserId { get; set; }
        public int PlayerId { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual User User { get; set; }
    }
}
