//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutineJobHa
    {
        public int RoutineJobHa1 { get; set; }
        public string Date { get; set; }
        public int RoutineJobId { get; set; }
        public bool IsCheck { get; set; }
    
        public virtual RoutineJob RoutineJob { get; set; }
    }
}
