//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SliderPhoto
    {
        public int SliderPhotoId { get; set; }
        public byte[] PhotoImg { get; set; }
        public string Header { get; set; }
        public string Matn { get; set; }
        public string URL { get; set; }
    }
}
