//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport
    {
        public int SportId { get; set; }
        public int CatId { get; set; }
        public string Date { get; set; }
        public int Tedad { get; set; }
        public Nullable<int> Set { get; set; }
    
        public virtual Cat Cat { get; set; }
    }
}
