//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreHoghogh
    {
        public int StoreHoghoghId { get; set; }
        public int PersonelId { get; set; }
        public int SHdate { get; set; }
        public int MazayaId { get; set; }
        public string MazRyialMah { get; set; }
    }
}
