//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taghvim_backUP_961111
    {
        public int TaghvimId { get; set; }
        public string DayDate { get; set; }
        public Nullable<int> IsHolyDay { get; set; }
        public int RoozHafte { get; set; }
        public string ChandShanbeh { get; set; }
        public Nullable<int> HafteChandom { get; set; }
    }
}
