//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageYourSelfMVC.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskImages = new HashSet<TaskImage>();
            this.Timings = new HashSet<Timing>();
        }
    
        public int TaskId { get; set; }
        public string Name { get; set; }
        public string DateStart { get; set; }
        public string DateEnd { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public Nullable<int> DarsadPishraft { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Olaviat { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> Rate { get; set; }
    
        public virtual Cat Cat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskImage> TaskImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timing> Timings { get; set; }
        public virtual Task Task1 { get; set; }
        public virtual Task Task2 { get; set; }
        public virtual User User { get; set; }
    }
}
